# Generated by Django 3.2.8 on 2023-01-13 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignyapp.student'),
        ),
    ]
