# Generated by Django 3.2.8 on 2023-02-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='mat_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
