# Generated by Django 4.0.6 on 2022-09-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignyapp.student'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
