# Generated by Django 3.2.8 on 2023-01-13 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0002_lecturer_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='link',
        ),
    ]
