# Generated by Django 3.2.8 on 2023-01-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0003_remove_lecturer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='mat_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
