# Generated by Django 4.0.6 on 2022-09-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0003_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
