# Generated by Django 3.2.8 on 2022-09-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0004_student_score_delete_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='relate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submit', to='assignyapp.lecturer'),
        ),
    ]
