# Generated by Django 3.2.8 on 2023-01-21 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0005_alter_lecturer_submit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_status', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='submit_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignyapp.submit_status'),
        ),
    ]
