# Generated by Django 3.2.8 on 2022-09-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0005_auto_20220914_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='relate',
        ),
        migrations.AddField(
            model_name='student',
            name='relate',
            field=models.ManyToManyField(null=True, related_name='submit', to='assignyapp.Lecturer'),
        ),
    ]
