# Generated by Django 3.2.8 on 2022-09-14 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0006_auto_20220914_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='relate',
        ),
        migrations.AddField(
            model_name='student',
            name='relate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submit', to='assignyapp.lecturer'),
        ),
    ]
