# Generated by Django 3.2.8 on 2023-01-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0007_auto_20230120_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='submit_status',
            field=models.CharField(default='submitted', max_length=255, null=True),
        ),
    ]
