# Generated by Django 3.2.8 on 2022-09-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0008_remove_student_relate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assign_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
