# Generated by Django 3.2.8 on 2023-01-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0008_alter_lecturer_submit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='submit_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
