# Generated by Django 3.2.8 on 2023-01-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0009_student_assign_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignyapp.lecturer'),
        ),
    ]
