# Generated by Django 4.0.5 on 2023-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignyapp', '0010_alter_student_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='attachment',
            field=models.FileField(upload_to='media/files'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attachment',
            field=models.FileField(upload_to='media/files'),
        ),
    ]
